language: python
python:
  - "3.6"

install:
  - pip install flake8 isort pytest pytest-cov codecov
  - pip install --editable .

script:
  - flake8 bottery
  - isort bottery --recursive --check-only
  - pytest --cov bottery

after_script:
  - codecov
